version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./:/app
    ports:
      - 8080:8080
  aws:
    image: anigeo/awscli
    environment:
      AWS_ACCESS_KEY_ID: "AKIAZNIXBIUUMORUW4XV"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_REGION: "us-east-1"    
      AWS_DEFAULT_REGION: "us-east-1"
    volumes:
      - ./:/app
    working_dir: /app
  terraform:
    build:
      dockerfile: terraform.Dockerfile
      context: .
    environment:
      AWS_ACCESS_KEY_ID: "AKIAZNIXBIUUMORUW4XV"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_REGION: "us-east-1"    
      AWS_DEFAULT_REGION: "us-east-1"
    volumes:
      - ./:/app
    working_dir: /app
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  website:
   build:
    context: .
   ports:
    - 80:80    
  integration-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - ./:/app
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/integration/*_spec.rb
  unit-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - ./:/app
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
